### ISSUE TITLE
Dict assignment to deep properties

### ISSUE THREAD

**Issue by nicolaskruchten** [jmmease/ipyplotly#1]
I just noticed some slightly inconsistent behaviour...

This works:

```python
f = Figure()
f.layout.margin = dict(l=10,r=10,b=10,t=10)
```

but this doesn't:

```python
f = Figure()
f.layout.hoverlabel.font = dict(family="Verdana")
```

but this does:

```python
f = Figure()
f.layout.hoverlabel = dict(font = dict(family="Verdana"))
```

**Comment by nicolaskruchten** [comment]
It's mostly an issue for the `font` type keys which are deeply nested, and in areas like `geo` which have a deep hierarchy. I stumbled across it trying to do this:

```python
f6.layout.geo.projection.rotation = dict(lat=20, lon=20, roll=20)
```

**Comment by jmmease** [comment]
Ahh, good catch. I'll take a look

**Comment by jmmease** [comment]
I think I found and fixed the issue. Just pushed update to master.

**Comment by nicolaskruchten** [comment]
Awesome, looks like it works as expected now :) Thanks!
